export const PRODUCT_FILTER = {
  PUT_MANUFACTURE_FILTER: "PUT_MANUFACTURE_FILTER",
  GET_MANUFACTURE_FILTER: "GET_MANUFACTURE_FILTER",
  PRICE_FILTER: "PRICE_FILTER",
  PUT_BRAND_FILTER: "PUT_BRAND_FILTER",
  GET_BRAND_FILTER: "GET_BRAND_FILTER",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  IS_FOUND_PRODUCTS: "IS_FOUND_PRODUCTS",
  FILTERED_PRODUCTS: "FILTERED_PRODUCTS",
};
