export const PRODUCT_FILTER = {
  PUT_MANUFACTURE_FILTER: "PUT_MANUFACTURE_FILTER",
  GET_MANUFACTURE_FILTER: "GET_MANUFACTURE_FILTER",
  PRICE_FILTER: "PRICE_FILTER",
  BRAND_FILTER: "BRAND_FILTER",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  NOT_FOUND_PRODUCTS: "NOT_FOUND_PRODUCTS",
};
